// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QT.DataB;

#nullable disable

namespace QT.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QT.Models.Documento", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<byte[]>("Arquivo")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("arquivo");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("categoria");

                    b.Property<string>("NomeDoArquivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProcessoCodigo")
                        .HasColumnType("int")
                        .HasColumnName("processoCodigo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("titulo");

                    b.HasKey("Codigo");

                    b.HasIndex("ProcessoCodigo");

                    b.ToTable("documentos");
                });

            modelBuilder.Entity("QT.Models.Processo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.HasKey("Codigo");

                    b.ToTable("processos");
                });

            modelBuilder.Entity("QT.Models.Documento", b =>
                {
                    b.HasOne("QT.Models.Processo", "Processo")
                        .WithMany()
                        .HasForeignKey("ProcessoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processo");
                });
#pragma warning restore 612, 618
        }
    }
}
